### ISSUE TITLE
It crashes when I run globalNavSwap with roadmap and helbing

### ISSUE THREAD

**Issue by douglasbandeiraivo** [MengeCrowdSim/Menge#116] opened 2019-03-25 13:09 UTC
It crashes when I run globalNavSwap examples with roadmap and helbing model.
![erro01](https://user-images.githubusercontent.com/13356499/54922008-f8ca5e00-4ee5-11e9-899c-328d7e63a147.JPG)
![erro02](https://user-images.githubusercontent.com/13356499/54922010-f8ca5e00-4ee5-11e9-9051-f50075e6c8bd.JPG)

**Comment by curds01** [comment] 2019-03-25 23:46
Thanks for posting; we'll take a look at this and see what we come up with.

**Comment by curds01** [comment] 2019-03-31 00:45
I finally got a window to examine it. I've confirmed the crash. The initial diagnosis is that there is a bug in the visibility query for finding the nearest node on the roadmap. I'm going to dig into it and find the bug. I believe this is most likely related to a bug I encountered years ago (but never resolved) in the maze example. In that case, a visibility query falsely reported visible, and, in this case, it's falsely reporting *not* visible. 

In the case of helbing, the repulsive forces are isotropic, so the agents on the left and right of the bottom row get pushed *back* and out. By pushing their initial position from `p_y="-4"` to `p_y="-3.6"`, they no longer get pushed into a "bad" location. 

I suspect that the agent is ever so slightly intersecting the the obstacles. If that's the case, the query will naturally fail due to the fact that no capsule from agent position to road map vertex will be collision free. 

If I'm lucky, that's what the problem is. In this case, it's not a "bug", per se, just a robustness issue. We can't generally prevent agents from penetrating obstacles, but the roadmap path computation should be robust enough to get them *out* of that configuration.

I'll weigh in later if I confirm/disprove my hypothesis and then subsequently notify of a fix.

**Comment by curds01** [comment] 2019-04-01 03:35
I've essentially determined the cause of the crash here. I have a PR in progress. There are a couple of things I still want to do in the PR, but if you want to take a peek, or steal the commit to address your issues, you can pull it from PR #118. Otherwise, I'll finish it off and then get it merged into master.

Thanks again for calling out this issue.

**Comment by douglasbandeiraivo** [comment] 2019-04-01 20:55
Thanks.

Em seg, 1 de abr de 2019 00:35, curds01 <notifications@github.com> escreveu:

**Closed** 2019-04-06 19:08 UTC
